CREATE TABLE users (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email           varchar(320) NOT NULL,
    phone_number    varchar(15) NOT NULL,
    name            varchar(100) NOT NULL,
    is_admin        boolean NOT NULL
);

CREATE TABLE user_passwords (
    user_id          integer PRIMARY KEY NOT NULL,
    password_hash    bytea NOT NULL,
    CONSTRAINT fk_password_user FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE user_secrets (
    user_id          integer PRIMARY KEY NOT NULL,
    password_salt    bytea NOT NULL,
    voting_secret    bytea NOT NULL,
    CONSTRAINT fk_secret_user FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE password_reset_codes (
    user_id      integer PRIMARY KEY NOT NULL,
    reset_code   varchar(10) NOT NULL,
    CONSTRAINT fk_resetcode_user FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE elections (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(512) NOT NULL,
    start_time  timestamp NOT NULL,
    end_time    timestamp NOT NULL
);

CREATE TABLE election_secrets (
    election_id  integer PRIMARY KEY NOT NULL,
    secret       bytea NOT NULL,
    CONSTRAINT fk_secret_election FOREIGN KEY(election_id) REFERENCES elections(id)
);

CREATE TABLE eligible_voters (
    user_id      integer NOT NULL,
    election_id  integer NOT NULL,
    has_voted    boolean NOT NULL,
    CONSTRAINT voter_election PRIMARY KEY (user_id, election_id),
    CONSTRAINT fk_voter_user FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_voter_election FOREIGN KEY(election_id) REFERENCES elections(id)
);

CREATE TABLE election_candidates (
    user_id      integer NOT NULL,
    election_id  integer NOT NULL,
    CONSTRAINT candidate_election PRIMARY KEY (user_id, election_id),
    CONSTRAINT fk_candidate_user FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_candidate_election FOREIGN KEY(election_id) REFERENCES elections(id)
);

CREATE TABLE election_results (
    user_id      integer NOT NULL,
    election_id  integer NOT NULL,
    votes        integer NOT NULL,
    CONSTRAINT candidate_election_result PRIMARY KEY (user_id, election_id),
    CONSTRAINT fk_result_user FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_result_election FOREIGN KEY(election_id) REFERENCES elections(id)
);

CREATE TABLE election_votes (
    id                         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    voted_candidate_id         integer,
    election_id                integer NOT NULL,
    vote_hash                  bytea NOT NULL,
    voted_candidate_encrypted  bytea NOT NULL,
    is_verified                boolean NOT NULL,
    CONSTRAINT fk_vote_candidate FOREIGN KEY(voted_candidate_id) REFERENCES users(id),
    CONSTRAINT fk_vote_election FOREIGN KEY(election_id) REFERENCES elections(id)
);

CREATE TABLE votes_otp (
    vote_id  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    otp_code varchar(10) NOT NULL,
    CONSTRAINT fk_otp_vote FOREIGN KEY(vote_id) REFERENCES election_votes(id)
);