CREATE TABLE Users (
    id      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email   varchar(320) NOT NULL,
    name    varchar(100) NOT NULL,
    isAdmin boolean NOT NULL
);

CREATE TABLE UsersPasswords (
    userId          integer PRIMARY KEY NOT NULL,
    passwordHash    bytea NOT NULL,
    passwordSalt    bytea NOT NULL,
    CONSTRAINT fk_password_user FOREIGN KEY(userId) REFERENCES Users(id)
);

CREATE TABLE Elections (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(512) NOT NULL,
    startTime   timestamp NOT NULL,
    endTime     timestamp NOT NULL
);

CREATE TABLE ElectionSecrets (
    electionId  integer PRIMARY KEY NOT NULL,
    secret      bytea NOT NULL,
    CONSTRAINT fk_secret_election FOREIGN KEY(electionId) REFERENCES Elections(id)
);

CREATE TABLE EligibleVoters (
    userId      integer NOT NULL,
    electionId  integer NOT NULL,
    CONSTRAINT voter_election PRIMARY KEY (userId, electionId),
    CONSTRAINT fk_voter_user FOREIGN KEY(userId) REFERENCES Users(id),
    CONSTRAINT fk_voter_election FOREIGN KEY(electionId) REFERENCES Elections(id)
);

CREATE TABLE ElectionCandidates (
    userId      integer NOT NULL,
    electionId  integer NOT NULL,
    CONSTRAINT candidate_election PRIMARY KEY (userId, electionId),
    CONSTRAINT fk_candidate_user FOREIGN KEY(userId) REFERENCES Users(id),
    CONSTRAINT fk_candidate_election FOREIGN KEY(electionId) REFERENCES Elections(id)
);

CREATE TABLE ElectionResults (
    userId      integer NOT NULL,
    electionId  integer NOT NULL,
    votes       integer NOT NULL,
    CONSTRAINT candidate_election_result PRIMARY KEY (userId, electionId),
    CONSTRAINT fk_result_user FOREIGN KEY(userId) REFERENCES Users(id),
    CONSTRAINT fk_result_election FOREIGN KEY(electionId) REFERENCES Elections(id)
);

CREATE TABLE ElectionVotes (
    id                      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    votedCandidateId        integer,
    electionId              integer NOT NULL,
    voteHash                bytea NOT NULL,
    votedCandidateEncrypted bytea NOT NULL,
    isVerified              boolean NOT NULL,
    CONSTRAINT fk_vote_candidate FOREIGN KEY(votedCandidateId) REFERENCES Users(id),
    CONSTRAINT fk_vote_election FOREIGN KEY(electionId) REFERENCES Elections(id)
);

CREATE TABLE VotesOTP (
    voteId  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    otpCode varchar(10) NOT NULL,
    CONSTRAINT fk_otp_vote FOREIGN KEY(voteId) REFERENCES ElectionVotes(id)
);